### ISSUE TITLE
configure: error:

### ISSUE THREAD

**Issue by whisper-bye** [zeromq/zmtpdump#2] opened 2017-03-12 08:55 UTC
./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by ajanicij** [comment] 2017-03-13 04:59
I see where the problem is: these files (install-sh etc.) are symbolic links to files in the directory /usr/share/automake-1.11. This is wrong and I will fix it as soon as I manage to find the time, which probably won't be before next weekend.

**Comment by ajanicij** [comment] 2017-03-13 05:11
Actually, I created a quick fix - I replaced the symbolic links with regular files. Once the pull request is merged, please try and let me know if it worked. (As far as I can see quickly, it should work if you have any version of automake installed. This doesn't seem right - configure script shouldn't rely on automake or autoconf, but the real fix will take me some time because my autotools knowledge is a bit rusty...)

**Comment by whisper-bye** [comment] 2017-03-13 05:16
thanks for your quick reply, I will check out it later.

**Comment by bluca** [comment] 2017-03-14 14:03
Fixed by https://github.com/zeromq/zmtpdump/pull/3

**Comment by bluca** [comment] 2017-03-14 14:04
normally these files are not checked in, and a simply autogen.sh generates them

also running autoreconf -fi should regenerate everything needed

**Closed by bluca** 2017-03-14 14:03 UTC
